### ISSUE TITLE
Document why some parameters of FREME requests may appear twice

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#142]
There are various parameters in FREME services that can be provided in two ways - via HTTP POST or as part of the URL (= HTTP GET), since some users prefer one of them. The HTTP GET approach has higher precedence. This may be worth documenting. An uniformed user for example may wonder whether she has to provide values twice.

**Comment by andish** [comment]
All requests for enrichment servises are POST requests. See simple documentation page.
I would say that there is rather a battle between HTTPS headers and query parameters. (on POST requests can be used both and this is the confusion).

Maybe the documentation would be improved - do not provide all parameter fields on one visible form, but split (maybe tabs): one for request with query parameters, other for HTTP headers.

**Comment by fsasaki** [comment]
"All requests for enrichment servises are POST requests. See simple documentation page.": yes, you are right, I should have set: HTTP POST allows for various ways to provide various parameters, headers vs. query parameters. And +1 to your suggestion.

**Comment by jnehring** [comment]
You can submit the parameters in many ways to FREME. The official ways are
- In the query string (same as in the URL)
- Header: informat, outformat, authorization username / password / token 

Then there is an undocumented way: You can set Content-Type "form-data" or "application/x-www-form-urlencoded" and submit the data in the post body. This is equal to submitting data in the query string. This is supported by the spring framework and I did not see a point in disabling this behaviour. But we do not support this and also do not mention it in the documentation.

For the official NIF parameters submitted via query string (input, informat, outformat, prefix) there are also short forms (i, f, o, p) which our API endpoints understand. I did not put the short form in the official API documentation because 3 ways of specifying input format is too much. The text "general information" on the full API documentation page mentions this.

Following this argumentation we could say that 2 ways to specify the same thing is also too much. So I suggest to remove all Content-Type and Accept headers from the individual API calls and move the information about headers to the "General" information.

I like this approach better then introducing tabs because it does not require us to re-program the API documentation. And I think the tabs are also somehow confusing.

>  An uniformed user for example may wonder whether she has to provide values twice.
> You do not have to provide the value twice. Once is enough.

**Comment by fsasaki** [comment]
Sounds good to me.

**Comment by jnehring** [comment]
Moved to #151
