### ISSUE TITLE
Create xslt demo

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#163]
In the FREME showroom

Copy from here:
[Working demo](http://fsasaki.github.io/stuff/xmlprague2016/demo)
[Source code](https://github.com/fsasaki/stuff/blob/gh-pages/xmlprague2016/demo/index.html)

**Comment by ArneBinder** [comment]
implemented.

**Comment by fsasaki** [comment]
One link target
http://api-dev.freme-project.eu/doc/freme-showcase/xml-to-rdf.html
should be fixed. @ArneBinder , can you make a copy of the HTML file xml-to-rdf.html and put it somewhere in the github repro so that it is accessible?

**Comment by ArneBinder** [comment]
@fsasaki which link target do you mean exactly? What kind of copy? You can access (and modify) the page [here](https://github.com/freme-project/Documentation/blob/master/_pages/freme-showcase/xml-to-rdf.html).

**Comment by fsasaki** [comment]
I mean this link
http://fsasaki.github.io/stuff/xmlprague2016/sasaki-et-al-xmlprague-2016.html
I would like to have a copy of that HTML page in the github repository -
but not sure where to store it so that the HTML page does not appear as
source code. Maybe have an gh-pages branch of the repro?

2016-02-09 13:48 GMT+01:00 ArneBinder notifications@github.com:

**Comment by jnehring** [comment]
@fsasaki the link http://fsasaki.github.io/stuff/xmlprague2016/sasaki-et-al-xmlprague-2016.html works now, right? So we can close the issue?

**Comment by fsasaki** [comment]
yes, thanks.
