### ISSUE TITLE
Create dataset tutorial does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#218]
The tutorial [ner using custom dataset](http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html) does not work in step 2. It misses an authentication token to create the dataset.

@ArneBinder please create a user on freme-dev and freme-live called "demo-user". Create an authentication token for this user and add this to the api calls in the tutorial. Also update the text of the tutorial and mention that it requires authentication, including a link to the authentication.

**Comment by ArneBinder** [comment]
I have added the user and the token to dev and live database. Furthermore added a prerequistes step, linking to authentication article and (disabled) fields showing the access token for the create / delete request. In think it is good to name all parameters send to the api, otherwise it could be confusing when users try to reproduce single steps by their own. @jnehring please have a look at the tutorial and close this, if it's sufficiant.

**Comment by jnehring** [comment]
Thank you!
