### ISSUE TITLE
workflow editor / e-entity mcafee dataset not found 

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#234]
In the FREME Workflow Editor
 http://api.freme-project.eu/freme-workflow-editor/
when I use the e-entity service and use the dataset mcafee I get the following error:

exception : eu.freme.common.exception.OwnedResourceNotFoundException 
path : /e-entity/freme-ner/documents 
message : Can not find DatasetMetadata with identifier='mcafee' 
error : Not Found 
status : 404

**Comment by jnehring** [comment]
I can reproduce the problem. The problem is that there is no mcaffee dataset and it should be removed from the dropdown.

Right now this is hard to fix, it would make sense to fix this first: https://github.com/freme-project/freme-workflow-editor/issues/22

We need to make a decision on the future of the freme workflow editor.

**Comment by ArneBinder** [comment]
Moved to https://github.com/freme-project/freme-workflow-editor/issues/24.
