### ISSUE TITLE
[Tutorials: NER against custom dataset] add paragraph: How to upload a large dataset

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#261]
In [this tutorial](http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html), @jnehring how should this look like? Via a file upload? Or just a description how to do this?

**Comment by jnehring** [comment]
Just a description how to do this. Should contain this information
- chunk the dataset
- use first the POST request to create the dataset, then PUT to update
- store the dataset in n-triples because this is easy to split by lines
- if possible, execute the script from the server that runs freme ner to speed up the process

There is a similar discussion here: https://github.com/freme-project/freme-ner/issues/114 . 

Please add a link to https://github.com/munnellg/freme_datasets also.

**Comment by ArneBinder** [comment]
Implemented first draft. @jnehring please have a look at [the paragraph How to upload a large dataset](http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html#upload-large-dataset).

**Comment by jnehring** [comment]
I changed the new content a bit and moved it to the bottom of the article. This issue is finished.
