### ISSUE TITLE
[Tutorial Getting started with FREME development] error during "Start FREME from the command line"

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#271]
See attached command line output. The error occurs then executing bin/start_local.sh

> bin/start_local.sh 
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> Fehler: Hauptklasse org.springframework.boot.loader.JarLauncher konnte nicht gefunden oder geladen werden

[freme-getting-started-log.txt](https://github.com/freme-project/Documentation/files/373510/freme-getting-started-log.txt)

**Comment by jnehring** [comment]
It workes on my ubuntu machine. This problem might be mac specific.

**Comment by jmschnei** [comment]
I have the same problem in my MAC machine. The next code worked for me:

> BASEDIR='dirname' "$0"
> BASEDIR='( cd "$BASEDIR" && pwd )'

**Comment by jnehring** [comment]
This code does not work out for me. It never finishes. Maybe we should have two start scripts, one for mac and one for linux.

**Comment by fsasaki** [comment]
+1.

**Comment by jnehring** [comment]
I added start_local_osx.sh to the package-maker. This should start FREME from OSX. I also upgraded the [broker-simple package](https://github.com/freme-project/freme-examples/tree/master/broker-simple) to  use the latest snapshot version of FREME so it includes the latest start script. @fsasaki or @jmschnei can you please test to download the broker-simple package, do mvn package and then start FREME using start_local_osx .sh ?

We need to remember to switch broker-simple to the next stable version after the next release because otherwise it will stop working after a while when one of the snapshot artifacts is no longer available.

**Comment by fsasaki** [comment]
I tried the installation and it works. The script start_local_osx .sh did not work. but the script start_local.sh worked :)

**Comment by jnehring** [comment]
Great. I tried the start_local.sh script and it works on linux as well. So I deleted the start_local_osx.sh script and the problem is solved.

I think I can explain: The artifact package-maker, that contains these start script, was used in version 0.3. There was a version 0.4, that (I guess) contained the start_local.sh file that fixes this problem. But this version was never used. When I updated the version of the package-maker in the broker-simple package I used version 0.5-SNAPSHOT, that contains the fixed start_local.sh and the new start_local_osx.sh.
