### ISSUE TITLE
Add documentation how to upload datasets to the server

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#278]
Please create a tutorial. There is an [article how to add documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/how-to-add-documentation.html). About the contents:
- Title: Upload datasets for entity linking to FREME NER
- Section: Upload a dataset to the server using [this script](https://github.com/munnellg/freme_datasets)
- Section: Upload DBPedia. I think this somehow differs from the rest.
- Section: Upload all datasets at once. This should provide some method to upload all the FREME datasets in a batch. Maybe with another script?

**Comment by m1ci** [comment]
@jnehring How will this tutorial differ from the one at 
http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html ?

**Comment by jnehring** [comment]
I do not think it is possible to upload the dbpedia dataset or any other real world dataset using http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html . So this will provide scripts how to upload the large datasets. In a future version this article will contain inforamtion how to convert the original datasets to skos.

But you are right. Maybe we should add this information to http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html instead of creating a new article.

**Comment by m1ci** [comment]
I think it is good to have own article for uploading such large datasets, only we need clearly to distinguish it from the current article. We can entitle it "Uploading large datasets into FREME NER". What do you think @jnehring?

**Comment by jnehring** [comment]
Ok then lets write a dedicated tutorial and call it "Uploading large datasets into FREME NER".

**Comment by sandroacoelho** [comment]
Hi @m1ci , @jnehring 

I've just expanded a little bit our current tutorial as follows. I am using [Freme Dataset Tool](https://github.com/munnellg/freme_datasets) to load our dev instance and it just works. Personally, I would recommend doing a fork to the organization.

---

**Uploading large datasets into FREME NER**

In a real world use case very large datasets are necessary. To make the upload of large datasets feasible you should consider the following hints:
- Chunk the dataset in chunks of e.g. 1000 lines each. When the dataset is too large then it does not fit in a single HTTP request. You can use split command with -n option to help you on this task;
- Start with an HTTP POST request to create a new dataset and upload the first chunk.
  
  E.g: 

`curl -v -d @dataset.nt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?name=NAME&description=DATASET_DESCRIPTION&informat=n-triples&outformat=json&language=en&token=YOUR_TOKEN_HERE" -H "Content-Type: text/plain"`

 Afterwards add the remaining chunks with HTTP PUT requests. This will add the data to the previously created dataset.

 E.g:

 `curl -X PUT -v -d @dataset.nt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?name=NAME&description=DATASET_DESCRIPTION&informat=n-triples&outformat=json&language=en&token=YOUR_TOKEN_HERE" -H "Content-Type: text/plain"`
- Use n-triples as serialization format for your dataset, if possible. This makes it easy to chunk the dataset because n-triples hold one triple a line.
- When is possible, execute the requests to upload the data from the same server that runs FREME-NER to speed up processing.

If you do not want to split your file in small chunks or curl is not familiar for you, We recommend to use [Freme Dataset Tool](https://github.com/munnellg/freme_datasets).

**Comment by jnehring** [comment]
Thanks for the documentation. We have a similar section at the end of [this article](https://freme-project.github.io/tutorials/entity-recognition-against-custom-dataset.html) so this issue can be closed.
