### ISSUE TITLE
[Tutorials] failing curl example

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#313]
The curl example in Step 2 of the Tutorial section from [translate_EN-NL_including_terminology.html](https://api-dev.freme-project.eu/doc/tutorials/translate_EN-NL_including_terminology.html) does not work.   

I think, the command should be like this:

```
curl -X POST -d @response-of-step1.ttl "https://api-dev.freme-project.eu/current/e-translation/tilde?informat=json-ld&outformat=json-ld&source-lang=en&target-lang=nl"
```

but it also results in : **Error Parsing NIF input**.

**Comment by jnehring** [comment]
In CURL you often have to set a content-type and accept header, otherwise it appends the query string parameters to the document body. Try this curl:

curl -X POST -d @response-of-step1.ttl  --header "Content-Type: applicatio/json+ld" --header "Accept: application/json+ld" "https://api-dev.freme-project.eu/current/e-translation/tilde?informat=json-ld&outformat=json-ld&source-lang=en&target-lang=nl"

When you change the curl: Can you please change the extension of the file from .ttl to .json? ttl is the extension for turtle and not for json.

**Comment by bgrusdt** [comment]
Thank you @jnehring , I have changed it and it should work now.
